// Daily quote bank for the Home screen.
//
// 884 short quotations, stepped through one per WEEKDAY by
// weekdayIndex() in index.html - roughly 3.4 years of Mon-Fri before it
// wraps. Themes are interleaved, so consecutive days rotate between stoicism,
// business, literature, science, leadership, sport, eastern philosophy, art,
// resilience and discipline rather than running in blocks.
//
// Attributions are best-effort: widely-circulated fakes were filtered out, but
// if you spot a misattribution just delete the line - order is not meaningful
// beyond the interleave, and removing one only shifts the sequence by a day.
//
// To refresh the bank (due ~2028), replace this array.

export const QUOTES = [
  { q: "You have power over your mind - not outside events. Realize this, and you will find strength.", a: "Marcus Aurelius" },
  { q: "Price is what you pay. Value is what you get.", a: "Warren Buffett" },
  { q: "This above all: to thine own self be true.", a: "William Shakespeare" },
  { q: "Nothing in life is to be feared, it is only to be understood.", a: "Marie Curie" },
  { q: "With malice toward none, with charity for all, with firmness in the right as God gives us to see the right.", a: "Abraham Lincoln" },
  { q: "Float like a butterfly, sting like a bee.", a: "Muhammad Ali" },
  { q: "A journey of a thousand miles begins with a single step.", a: "Lao Tzu" },
  { q: "Inspiration exists, but it has to find you working.", a: "Pablo Picasso" },
  { q: "Everything can be taken from a man but one thing: the last of the human freedoms - to choose one's attitude.", a: "Viktor Frankl" },
  { q: "Practice does not make perfect. Only perfect practice makes perfect.", a: "Vince Lombardi" },
  { q: "Waste no more time arguing about what a good man should be. Be one.", a: "Marcus Aurelius" },
  { q: "It's far better to buy a wonderful company at a fair price than a fair company at a wonderful price.", a: "Warren Buffett" },
  { q: "We know what we are, but know not what we may be.", a: "William Shakespeare" },
  { q: "I am among those who think that science has great beauty.", a: "Marie Curie" },
  { q: "Let us have faith that right makes might, and in that faith let us dare to do our duty as we understand it.", a: "Abraham Lincoln" },
  { q: "I am the greatest.", a: "Muhammad Ali" },
  { q: "He who knows does not speak. He who speaks does not know.", a: "Lao Tzu" },
  { q: "Every child is an artist. The problem is how to remain an artist once he grows up.", a: "Pablo Picasso" },
  { q: "When we are no longer able to change a situation, we are challenged to change ourselves.", a: "Viktor Frankl" },
  { q: "Write a short story every week. It's not possible to write 52 bad stories in a row.", a: "Ray Bradbury" },
  { q: "The impediment to action advances action. What stands in the way becomes the way.", a: "Marcus Aurelius" },
  { q: "Be fearful when others are greedy and greedy when others are fearful.", a: "Warren Buffett" },
  { q: "Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.", a: "William Shakespeare" },
  { q: "Imagination is more important than knowledge.", a: "Albert Einstein" },
  { q: "A house divided against itself cannot stand.", a: "Abraham Lincoln" },
  { q: "It's not bragging if you can back it up.", a: "Muhammad Ali" },
  { q: "Knowing others is wisdom; knowing yourself is enlightenment.", a: "Lao Tzu" },
  { q: "If you hear a voice within you say you cannot paint, then by all means paint, and that voice will be silenced.", a: "Vincent van Gogh" },
  { q: "What is to give light must endure burning.", a: "Viktor Frankl" },
  { q: "I write when I'm inspired, and I see to it that I'm inspired at nine o'clock every morning.", a: "Peter De Vries" },
  { q: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", a: "Marcus Aurelius" },
  { q: "Risk comes from not knowing what you are doing.", a: "Warren Buffett" },
  { q: "Love all, trust a few, do wrong to none.", a: "William Shakespeare" },
  { q: "The most beautiful thing we can experience is the mysterious. It is the source of all true art and science.", a: "Albert Einstein" },
  { q: "The dogmas of the quiet past are inadequate to the stormy present.", a: "Abraham Lincoln" },
  { q: "The man who has no imagination has no wings.", a: "Muhammad Ali" },
  { q: "The softest things in the world overcome the hardest things in the world.", a: "Lao Tzu" },
  { q: "Great things are not done by impulse, but by a series of small things brought together.", a: "Vincent van Gogh" },
  { q: "In some ways suffering ceases to be suffering at the moment it finds a meaning.", a: "Viktor Frankl" },
  { q: "Creativity is a habit, and the best creativity is the result of good work habits.", a: "Twyla Tharp" },
  { q: "If it is not right, do not do it, if it is not true, do not say it.", a: "Marcus Aurelius" },
  { q: "It takes 20 years to build a reputation and five minutes to ruin it.", a: "Warren Buffett" },
  { q: "How far that little candle throws his beams! So shines a good deed in a naughty world.", a: "William Shakespeare" },
  { q: "What I cannot create, I do not understand.", a: "Richard Feynman" },
  { q: "As I would not be a slave, so I would not be a master.", a: "Abraham Lincoln" },
  { q: "Don't count the days. Make the days count.", a: "Muhammad Ali" },
  { q: "The Tao that can be told is not the eternal Tao.", a: "Lao Tzu" },
  { q: "I am seeking, I am striving, I am in it with all my heart.", a: "Vincent van Gogh" },
  { q: "Although the world is full of suffering, it is also full of the overcoming of it.", a: "Helen Keller" },
  { q: "First forget inspiration. Habit is more dependable. Habit will sustain you whether you're inspired or not.", a: "Octavia Butler" },
  { q: "The best revenge is to be unlike him who performed the injury.", a: "Marcus Aurelius" },
  { q: "Someone is sitting in the shade today because someone planted a tree a long time ago.", a: "Warren Buffett" },
  { q: "There is nothing either good or bad, but thinking makes it so.", a: "William Shakespeare" },
  { q: "The first principle is that you must not fool yourself, and you are the easiest person to fool.", a: "Richard Feynman" },
  { q: "Government of the people, by the people, for the people, shall not perish from the earth.", a: "Abraham Lincoln" },
  { q: "He who is not courageous enough to take risks will accomplish nothing in life.", a: "Muhammad Ali" },
  { q: "Do the difficult things while they are easy.", a: "Lao Tzu" },
  { q: "What would life be if we had no courage to attempt anything?", a: "Vincent van Gogh" },
  { q: "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.", a: "Helen Keller" },
  { q: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", a: "Bruce Lee" },
  { q: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", a: "Marcus Aurelius" },
  { q: "Only when the tide goes out do you discover who's been swimming naked.", a: "Warren Buffett" },
  { q: "Nothing great was ever achieved without enthusiasm.", a: "Ralph Waldo Emerson" },
  { q: "If I have seen further it is by standing on the shoulders of giants.", a: "Isaac Newton" },
  { q: "The occasion is piled high with difficulty, and we must rise with the occasion.", a: "Abraham Lincoln" },
  { q: "I've failed over and over and over again in my life, and that is why I succeed.", a: "Michael Jordan" },
  { q: "He who is contented is rich.", a: "Lao Tzu" },
  { q: "I found I could say things with color and shapes that I couldn't say any other way, things I had no words for.", a: "Georgia O'Keeffe" },
  { q: "Keep your face to the sunshine and you cannot see a shadow.", a: "Helen Keller" },
  { q: "I hated every minute of training, but I said, don't quit. Suffer now and live the rest of your life as a champion.", a: "Muhammad Ali" },
  { q: "Confine yourself to the present.", a: "Marcus Aurelius" },
  { q: "Our favorite holding period is forever.", a: "Warren Buffett" },
  { q: "Trust thyself: every heart vibrates to that iron string.", a: "Ralph Waldo Emerson" },
  { q: "To myself I seem to have been only like a boy playing on the seashore, while the great ocean of truth lay all undiscovered before me.", a: "Isaac Newton" },
  { q: "In giving freedom to the slave, we assure freedom to the free.", a: "Abraham Lincoln" },
  { q: "I can accept failure, everyone fails at something. But I can't accept not trying.", a: "Michael Jordan" },
  { q: "To know that you do not know is the best.", a: "Lao Tzu" },
  { q: "To create one's world in any of the arts takes courage.", a: "Georgia O'Keeffe" },
  { q: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", a: "Helen Keller" },
  { q: "The fight is won or lost far away from witnesses, behind the lines, in the gym, and out there on the road.", a: "Muhammad Ali" },
  { q: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", a: "Marcus Aurelius" },
  { q: "You only have to do a very few things right in your life so long as you don't do too many things wrong.", a: "Warren Buffett" },
  { q: "A foolish consistency is the hobgoblin of little minds.", a: "Ralph Waldo Emerson" },
  { q: "We are made of star stuff.", a: "Carl Sagan" },
  { q: "Never give in, never give in, never, never, never.", a: "Winston Churchill" },
  { q: "Talent wins games, but teamwork and intelligence win championships.", a: "Michael Jordan" },
  { q: "Thirty spokes share the wheel's hub; it is the center hole that makes it useful.", a: "Lao Tzu" },
  { q: "Nobody sees a flower really; it is so small. We haven't time, and to see takes time.", a: "Georgia O'Keeffe" },
  { q: "Life is either a daring adventure or nothing.", a: "Helen Keller" },
  { q: "If people knew how hard I worked to get my mastery, it would not seem so wonderful at all.", a: "Michelangelo" },
  { q: "Loss is nothing else but change, and change is Nature's delight.", a: "Marcus Aurelius" },
  { q: "The most important thing to do if you find yourself in a hole is to stop digging.", a: "Warren Buffett" },
  { q: "The only way to have a friend is to be one.", a: "Ralph Waldo Emerson" },
  { q: "Extraordinary claims require extraordinary evidence.", a: "Carl Sagan" },
  { q: "We shall defend our island, whatever the cost may be.", a: "Winston Churchill" },
  { q: "Some people want it to happen, some wish it would happen, others make it happen.", a: "Michael Jordan" },
  { q: "Returning is the motion of the Tao.", a: "Lao Tzu" },
  { q: "I have been absolutely terrified every moment of my life and I have never let it keep me from doing a single thing I wanted to do.", a: "Georgia O'Keeffe" },
  { q: "Nothing can dim the light which shines from within.", a: "Maya Angelou" },
  { q: "Dripping water hollows out stone, not through force but through persistence.", a: "Ovid" },
  { q: "Be like the rocky headland on which the waves constantly break.", a: "Marcus Aurelius" },
  { q: "In the business world, the rearview mirror is always clearer than the windshield.", a: "Warren Buffett" },
  { q: "Every wall is a door.", a: "Ralph Waldo Emerson" },
  { q: "However difficult life may seem, there is always something you can do and succeed at.", a: "Stephen Hawking" },
  { q: "I have nothing to offer but blood, toil, tears and sweat.", a: "Winston Churchill" },
  { q: "A champion is defined not by their wins but by how they can recover when they fall.", a: "Serena Williams" },
  { q: "Learning without thought is labor lost; thought without learning is perilous.", a: "Confucius" },
  { q: "Making your unknown known is the important thing.", a: "Georgia O'Keeffe" },
  { q: "I can be changed by what happens to me. But I refuse to be reduced by it.", a: "Maya Angelou" },
  { q: "Practice is the best of all instructors.", a: "Publilius Syrus" },
  { q: "Nowhere can man find a quieter or more untroubled retreat than in his own soul.", a: "Marcus Aurelius" },
  { q: "Honesty is a very expensive gift. Don't expect it from cheap people.", a: "Warren Buffett" },
  { q: "I went to the woods because I wished to live deliberately.", a: "Henry David Thoreau" },
  { q: "Remember to look up at the stars and not down at your feet.", a: "Stephen Hawking" },
  { q: "Now this is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning.", a: "Winston Churchill" },
  { q: "The success of every woman should be the inspiration to another.", a: "Serena Williams" },
  { q: "Do not impose on others what you do not desire yourself.", a: "Confucius" },
  { q: "I paint myself because I am so often alone and because I am the subject I know best.", a: "Frida Kahlo" },
  { q: "Courage is the most important of all the virtues, because without courage you can't practice any other virtue consistently.", a: "Maya Angelou" },
  { q: "The secret of success is constancy to purpose.", a: "Benjamin Disraeli" },
  { q: "Reject your sense of injury and the injury itself disappears.", a: "Marcus Aurelius" },
  { q: "I insist on a lot of time being spent, almost every day, to just sit and think.", a: "Warren Buffett" },
  { q: "Only that day dawns to which we are awake.", a: "Henry David Thoreau" },
  { q: "The present is theirs; the future, for which I really worked, is mine.", a: "Nikola Tesla" },
  { q: "Victory at all costs, victory in spite of all terror, victory however long and hard the road may be.", a: "Winston Churchill" },
  { q: "No human is limited.", a: "Eliud Kipchoge" },
  { q: "The superior man is modest in his speech, but exceeds in his actions.", a: "Confucius" },
  { q: "Feet, what do I need you for when I have wings to fly?", a: "Frida Kahlo" },
  { q: "History, despite its wrenching pain, cannot be unlived, but if faced with courage, need not be lived again.", a: "Maya Angelou" },
  { q: "Great things are done by a series of small things brought together.", a: "Vincent van Gogh" },
  { q: "The soul becomes dyed with the color of its thoughts.", a: "Marcus Aurelius" },
  { q: "The best thing I did was to choose the right heroes.", a: "Warren Buffett" },
  { q: "Live in each season as it passes; breathe the air, drink the drink, taste the fruit.", a: "Henry David Thoreau" },
  { q: "The scientific man does not aim at an immediate result.", a: "Nikola Tesla" },
  { q: "Never was so much owed by so many to so few.", a: "Winston Churchill" },
  { q: "Only the disciplined ones in life are free. If you are undisciplined, you are a slave to your moods and your passions.", a: "Eliud Kipchoge" },
  { q: "When we see men of a contrary character, we should turn inwards and examine ourselves.", a: "Confucius" },
  { q: "I paint flowers so they will not die.", a: "Frida Kahlo" },
  { q: "It happened, therefore it can happen again.", a: "Primo Levi" },
  { q: "I don't wait for moods. You accomplish nothing if you do that. Your mind must know it has got to get down to work.", a: "Pearl S. Buck" },
  { q: "Do every act of your life as though it were the last act of your life.", a: "Marcus Aurelius" },
  { q: "Take the high road, it's far less crowded.", a: "Warren Buffett" },
  { q: "It's not what you look at that matters, it's what you see.", a: "Henry David Thoreau" },
  { q: "Genius is one percent inspiration and ninety-nine percent perspiration.", a: "Thomas Edison" },
  { q: "Courage is rightly esteemed the first of human qualities because it is the quality which guarantees all others.", a: "Winston Churchill" },
  { q: "I want to run with a happy heart and a happy mind.", a: "Eliud Kipchoge" },
  { q: "When I walk along with two others, they may serve me as my teachers.", a: "Confucius" },
  { q: "Creativity takes courage.", a: "Henri Matisse" },
  { q: "Monsters exist, but they are too few in number to be truly dangerous.", a: "Primo Levi" },
  { q: "A writer who waits for ideal conditions under which to work will die without putting a word on paper.", a: "E. B. White" },
  { q: "Never let the future disturb you. You will meet it with the same weapons of reason which today arm you against the present.", a: "Marcus Aurelius" },
  { q: "The big money is not in the buying and selling, but in the waiting.", a: "Charlie Munger" },
  { q: "I celebrate myself, and sing myself.", a: "Walt Whitman" },
  { q: "Many of life's failures are people who did not realize how close they were to success when they gave up.", a: "Thomas Edison" },
  { q: "It is no use saying, We are doing our best. You have got to succeed in doing what is necessary.", a: "Winston Churchill" },
  { q: "The man who can drive himself further once the effort gets painful is the man who will win.", a: "Roger Bannister" },
  { q: "When you know a thing, hold that you know it; when you do not know a thing, allow that you do not know it.", a: "Confucius" },
  { q: "There are always flowers for those who want to see them.", a: "Henri Matisse" },
  { q: "There may be times when we are powerless to prevent injustice, but there must never be a time when we fail to protest.", a: "Elie Wiesel" },
  { q: "The harder I practice, the luckier I get.", a: "Gary Player" },
  { q: "How much time he gains who does not look to see what his neighbor says or does or thinks.", a: "Marcus Aurelius" },
  { q: "Invert, always invert.", a: "Charlie Munger" },
  { q: "Do I contradict myself? Very well then I contradict myself, (I am large, I contain multitudes.)", a: "Walt Whitman" },
  { q: "The Analytical Engine weaves algebraic patterns just as the Jacquard loom weaves flowers and leaves.", a: "Ada Lovelace" },
  { q: "Democracy is the worst form of Government except for all those other forms that have been tried from time to time.", a: "Winston Churchill" },
  { q: "It is the brain, not the heart or lungs, that is the critical organ.", a: "Roger Bannister" },
  { q: "All that we are is the result of what we have thought.", a: "Buddha" },
  { q: "An artist must never be a prisoner of himself, prisoner of style, prisoner of reputation, prisoner of success.", a: "Henri Matisse" },
  { q: "Because I remember, I despair. Because I remember, I have the duty to reject despair.", a: "Elie Wiesel" },
  { q: "The secret is in the dirt.", a: "Ben Hogan" },
  { q: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", a: "Marcus Aurelius" },
  { q: "Spend each day trying to be a little wiser than you were when you woke up.", a: "Charlie Munger" },
  { q: "That the powerful play goes on, and you may contribute a verse.", a: "Walt Whitman" },
  { q: "That brain of mine is something more than merely mortal, as time will show.", a: "Ada Lovelace" },
  { q: "Injustice anywhere is a threat to justice everywhere.", a: "Martin Luther King Jr" },
  { q: "To give anything less than your best is to sacrifice the gift.", a: "Steve Prefontaine" },
  { q: "Hatred does not cease by hatred, but only by love; this is the eternal rule.", a: "Buddha" },
  { q: "What I dream of is an art of balance, of purity and serenity.", a: "Henri Matisse" },
  { q: "Hope is like peace. It is not a gift from God. It is a gift only we can give one another.", a: "Elie Wiesel" },
  { q: "You have to expect things of yourself before you can do them.", a: "Michael Jordan" },
  { q: "Dig within. Within is the wellspring of Good; and it is always ready to bubble up, if you just dig.", a: "Marcus Aurelius" },
  { q: "It is remarkable how much long-term advantage people like us have gotten by trying to be consistently not stupid.", a: "Charlie Munger" },
  { q: "Resist much, obey little.", a: "Walt Whitman" },
  { q: "The most damaging phrase in the language is: we've always done it this way.", a: "Grace Hopper" },
  { q: "The arc of the moral universe is long, but it bends toward justice.", a: "Martin Luther King Jr" },
  { q: "Somebody may beat me, but they are going to have to bleed to do it.", a: "Steve Prefontaine" },
  { q: "Better than a thousand hollow words is one word that brings peace.", a: "Buddha" },
  { q: "Inspiration is for amateurs. The rest of us just show up and get to work.", a: "Chuck Close" },
  { q: "In spite of everything I still believe that people are really good at heart.", a: "Anne Frank" },
  { q: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and love of what you are doing.", a: "Pele" },
  { q: "That which is not good for the beehive cannot be good for the bees.", a: "Marcus Aurelius" },
  { q: "Show me the incentive and I will show you the outcome.", a: "Charlie Munger" },
  { q: "Be patient toward all that is unsolved in your heart and try to love the questions themselves.", a: "Rainer Maria Rilke" },
  { q: "It is easier to ask forgiveness than it is to get permission.", a: "Grace Hopper" },
  { q: "Our lives begin to end the day we become silent about things that matter.", a: "Martin Luther King Jr" },
  { q: "A lot of people run a race to see who is fastest. I run to see who has the most guts.", a: "Steve Prefontaine" },
  { q: "Irrigators channel waters; fletchers straighten arrows; the wise master themselves.", a: "Buddha" },
  { q: "All the best ideas come out of the process; they come out of the work itself.", a: "Chuck Close" },
  { q: "I don't think of all the misery, but of the beauty that still remains.", a: "Anne Frank" },
  { q: "Only the disciplined ones in life are free.", a: "Eliud Kipchoge" },
  { q: "Think of yourself as dead. You have lived your life. Now take what is left and live it properly.", a: "Marcus Aurelius" },
  { q: "To the man with only a hammer, every problem looks like a nail.", a: "Charlie Munger" },
  { q: "Let everything happen to you: beauty and terror. Just keep going. No feeling is final.", a: "Rainer Maria Rilke" },
  { q: "We can only see a short distance ahead, but we can see plenty there that needs to be done.", a: "Alan Turing" },
  { q: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", a: "Martin Luther King Jr" },
  { q: "If you want to run, run a mile. If you want to experience a different life, run a marathon.", a: "Emil Zatopek" },
  { q: "As a solid rock is not shaken by the wind, so the wise are not moved by praise or blame.", a: "Buddha" },
  { q: "Good design is as little design as possible.", a: "Dieter Rams" },
  { q: "Think of all the beauty still left around you and be happy.", a: "Anne Frank" },
  { q: "When you are not practicing, remember, someone somewhere is practicing, and when you meet him he will win.", a: "Bill Bradley" },
  { q: "Ambition means tying your well-being to what other people say or do.", a: "Marcus Aurelius" },
  { q: "Knowing what you don't know is more useful than being brilliant.", a: "Charlie Munger" },
  { q: "Perhaps all the dragons in our lives are princesses waiting to see us act, just once, with beauty and courage.", a: "Rainer Maria Rilke" },
  { q: "Machines take me by surprise with great frequency.", a: "Alan Turing" },
  { q: "The time is always right to do what is right.", a: "Martin Luther King Jr" },
  { q: "It's at the borders of pain and suffering that the men are separated from the boys.", a: "Emil Zatopek" },
  { q: "Conquer anger by non-anger. Conquer evil by good. Conquer the stingy by giving.", a: "Buddha" },
  { q: "Less, but better.", a: "Dieter Rams" },
  { q: "Where there's hope, there's life. It fills us with fresh courage and makes us strong again.", a: "Anne Frank" },
  { q: "Habit is habit, and not to be flung out of the window by any man, but coaxed downstairs a step at a time.", a: "Mark Twain" },
  { q: "To love only what happens, what was destined. No greater harmony.", a: "Marcus Aurelius" },
  { q: "The first rule of compounding: never interrupt it unnecessarily.", a: "Charlie Munger" },
  { q: "Live the questions now.", a: "Rainer Maria Rilke" },
  { q: "In mathematics you don't understand things. You just get used to them.", a: "John von Neumann" },
  { q: "A man who won't die for something is not fit to live.", a: "Martin Luther King Jr" },
  { q: "An athlete cannot run with money in his pockets. He must run with hope in his heart.", a: "Emil Zatopek" },
  { q: "Heedfulness is the path to the deathless; heedlessness is the path to death.", a: "Buddha" },
  { q: "Indifference towards people and the reality in which they live is the one and only cardinal sin in design.", a: "Dieter Rams" },
  { q: "I can shake off everything as I write; my sorrows disappear, my courage is reborn.", a: "Anne Frank" },
  { q: "Habit is a cable; we weave a thread of it every day, and at last we cannot break it.", a: "Horace Mann" },
  { q: "It is not death that a man should fear, but he should fear never beginning to live.", a: "Marcus Aurelius" },
  { q: "Take a simple idea and take it seriously.", a: "Charlie Munger" },
  { q: "The two most powerful warriors are patience and time.", a: "Leo Tolstoy" },
  { q: "If people do not believe that mathematics is simple, it is only because they do not realize how complicated life is.", a: "John von Neumann" },
  { q: "We must accept finite disappointment, but never lose infinite hope.", a: "Martin Luther King Jr" },
  { q: "If you have a body, you are an athlete.", a: "Bill Bowerman" },
  { q: "Be islands unto yourselves, refuges unto yourselves, seeking no external refuge.", a: "Buddha" },
  { q: "The details are not the details. They make the design.", a: "Charles Eames" },
  { q: "I have often marvelled at the thin line that separates success from failure.", a: "Ernest Shackleton" },
  { q: "Habit is either the best of servants or the worst of masters.", a: "Nathaniel Emmons" },
  { q: "When you arise in the morning, think of what a precious privilege it is to be alive.", a: "Marcus Aurelius" },
  { q: "A great business at a fair price is superior to a fair business at a great price.", a: "Charlie Munger" },
  { q: "If you want to be happy, be.", a: "Leo Tolstoy" },
  { q: "Science is not a collection of truths. It is a continuing exploration of mysteries.", a: "Freeman Dyson" },
  { q: "Faith is taking the first step even when you don't see the whole staircase.", a: "Martin Luther King Jr" },
  { q: "The real purpose of running isn't to win a race. It's to test the limits of the human heart.", a: "Bill Bowerman" },
  { q: "All conditioned things are impermanent. Work out your own salvation with diligence.", a: "Buddha" },
  { q: "Take your pleasure seriously.", a: "Charles Eames" },
  { q: "It always seems impossible until it's done.", a: "Nelson Mandela" },
  { q: "Nothing is particularly hard if you divide it into small jobs.", a: "Henry Ford" },
  { q: "The universe is change; our life is what our thoughts make it.", a: "Marcus Aurelius" },
  { q: "The best armor of old age is a well spent life preceding it.", a: "Charlie Munger" },
  { q: "Beauty will save the world.", a: "Fyodor Dostoevsky" },
  { q: "It is characteristic of all deep human problems that they are not to be approached without some humility.", a: "Freeman Dyson" },
  { q: "The ultimate measure of a man is where he stands in moments of challenge and controversy.", a: "Martin Luther King Jr" },
  { q: "Failure to prepare is preparing to fail.", a: "John Wooden" },
  { q: "The fish trap exists because of the fish; once you have gotten the fish, you can forget the trap.", a: "Zhuangzi" },
  { q: "Eventually everything connects.", a: "Charles Eames" },
  { q: "Do not judge me by my successes, judge me by how many times I fell down and got back up again.", a: "Nelson Mandela" },
  { q: "Our main business is not to see what lies dimly at a distance, but to do what lies clearly at hand.", a: "Thomas Carlyle" },
  { q: "Adapt yourself to the things among which your lot has been cast.", a: "Marcus Aurelius" },
  { q: "You don't have to pee on an electric fence to learn not to do it.", a: "Charlie Munger" },
  { q: "Love all God's creation, the whole and every grain of sand of it.", a: "Fyodor Dostoevsky" },
  { q: "When you can measure what you are speaking about, and express it in numbers, you know something about it.", a: "Lord Kelvin" },
  { q: "Freedom is never voluntarily given by the oppressor; it must be demanded by the oppressed.", a: "Martin Luther King Jr" },
  { q: "Be quick, but don't hurry.", a: "John Wooden" },
  { q: "The perfect man uses his mind like a mirror. It grasps nothing, it refuses nothing.", a: "Zhuangzi" },
  { q: "Design is a plan for arranging elements in such a way as best to accomplish a particular purpose.", a: "Charles Eames" },
  { q: "Difficulties break some men but make others.", a: "Nelson Mandela" },
  { q: "Every noble work is at first impossible.", a: "Thomas Carlyle" },
  { q: "We suffer more often in imagination than in reality.", a: "Seneca" },
  { q: "There is no better teacher than history in determining the future.", a: "Charlie Munger" },
  { q: "Man only likes to count his troubles; he doesn't calculate his happiness.", a: "Fyodor Dostoevsky" },
  { q: "I never satisfy myself until I can make a mechanical model of a thing.", a: "Lord Kelvin" },
  { q: "It always seems impossible until it is done.", a: "Nelson Mandela" },
  { q: "Don't let what you cannot do interfere with what you can do.", a: "John Wooden" },
  { q: "Great understanding is broad and unhurried; little understanding is cramped and busy.", a: "Zhuangzi" },
  { q: "The role of the designer is that of a very good, thoughtful host anticipating the needs of his guests.", a: "Charles Eames" },
  { q: "After climbing a great hill, one only finds that there are many more hills to climb.", a: "Nelson Mandela" },
  { q: "The years teach much which the days never know.", a: "Ralph Waldo Emerson" },
  { q: "It is not that we have a short time to live, but that we waste a lot of it.", a: "Seneca" },
  { q: "The greatest danger in times of turbulence is not the turbulence, it is to act with yesterday's logic.", a: "Peter Drucker" },
  { q: "The world breaks everyone, and afterward, many are strong at the broken places.", a: "Ernest Hemingway" },
  { q: "In the fields of observation, chance favors only the prepared mind.", a: "Louis Pasteur" },
  { q: "I learned that courage was not the absence of fear, but the triumph over it.", a: "Nelson Mandela" },
  { q: "It's what you learn after you know it all that counts.", a: "John Wooden" },
  { q: "When the shoe fits, the foot is forgotten.", a: "Zhuangzi" },
  { q: "What works good is better than what looks good, because what works good lasts.", a: "Ray Eames" },
  { q: "One child, one teacher, one book, one pen can change the world.", a: "Malala Yousafzai" },
  { q: "The reward of a thing well done is to have done it.", a: "Ralph Waldo Emerson" },
  { q: "Luck is what happens when preparation meets opportunity.", a: "Seneca" },
  { q: "There is nothing so useless as doing efficiently that which should not be done at all.", a: "Peter Drucker" },
  { q: "A man can be destroyed but not defeated.", a: "Ernest Hemingway" },
  { q: "Science knows no country, because knowledge belongs to humanity.", a: "Louis Pasteur" },
  { q: "Education is the most powerful weapon which you can use to change the world.", a: "Nelson Mandela" },
  { q: "Never mistake activity for achievement.", a: "John Wooden" },
  { q: "I do not know whether I was a man dreaming I was a butterfly, or am now a butterfly dreaming I am a man.", a: "Zhuangzi" },
  { q: "Don't only practice your art, but force your way into its secrets.", a: "Ludwig van Beethoven" },
  { q: "When the whole world is silent, even one voice becomes powerful.", a: "Malala Yousafzai" },
  { q: "It is not enough to be busy. So are the ants. The question is: What are we busy about?", a: "Henry David Thoreau" },
  { q: "Difficulties strengthen the mind, as labor does the body.", a: "Seneca" },
  { q: "The best way to predict the future is to create it.", a: "Peter Drucker" },
  { q: "Courage is grace under pressure.", a: "Ernest Hemingway" },
  { q: "Research is what I'm doing when I don't know what I'm doing.", a: "Wernher von Braun" },
  { q: "To be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.", a: "Nelson Mandela" },
  { q: "Make each day your masterpiece.", a: "John Wooden" },
  { q: "To study the Buddha way is to study the self. To study the self is to forget the self.", a: "Dogen" },
  { q: "I was obliged to be industrious. Whoever is equally industrious will succeed equally well.", a: "Johann Sebastian Bach" },
  { q: "I raise up my voice not so that I can shout, but so that those without a voice can be heard.", a: "Malala Yousafzai" },
  { q: "The heights by great men reached and kept were not attained by sudden flight.", a: "Henry Wadsworth Longfellow" },
  { q: "Every new beginning comes from some other beginning's end.", a: "Seneca" },
  { q: "Management is doing things right; leadership is doing the right things.", a: "Peter Drucker" },
  { q: "There is no gate, no lock, no bolt that you can set upon the freedom of my mind.", a: "Virginia Woolf" },
  { q: "I have learned to use the word impossible with the greatest caution.", a: "Wernher von Braun" },
  { q: "It is in your hands to make a better world for all who live in it.", a: "Nelson Mandela" },
  { q: "Winning is not a sometime thing; it's an all the time thing.", a: "Vince Lombardi" },
  { q: "To forget the self is to be enlightened by the ten thousand things.", a: "Dogen" },
  { q: "There's nothing remarkable about it. All one has to do is hit the right keys at the right time and the instrument plays itself.", a: "Johann Sebastian Bach" },
  { q: "Let us pick up our books and our pens. They are our most powerful weapons.", a: "Malala Yousafzai" },
  { q: "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", a: "Samuel Beckett" },
  { q: "He who is brave is free.", a: "Seneca" },
  { q: "What gets measured gets improved.", a: "Peter Drucker" },
  { q: "One cannot think well, love well, sleep well, if one has not dined well.", a: "Virginia Woolf" },
  { q: "There was no choice but to be pioneers.", a: "Margaret Hamilton" },
  { q: "I have cherished the ideal of a democratic and free society in which all persons live together in harmony.", a: "Nelson Mandela" },
  { q: "The measure of who we are is what we do with what we have.", a: "Vince Lombardi" },
  { q: "If you cannot find the truth right where you are, where else do you expect to find it?", a: "Dogen" },
  { q: "Do not fear mistakes. There are none.", a: "Miles Davis" },
  { q: "I don't want to be remembered as the girl who was shot. I want to be remembered as the girl who stood up.", a: "Malala Yousafzai" },
  { q: "Show up, show up, show up, and after a while the muse shows up, too.", a: "Isabel Allende" },
  { q: "As long as you live, keep learning how to live.", a: "Seneca" },
  { q: "Culture eats strategy for breakfast.", a: "Peter Drucker" },
  { q: "No need to hurry. No need to sparkle. No need to be anybody but oneself.", a: "Virginia Woolf" },
  { q: "When I first got into it, nobody knew what it was that we were doing. It was like the Wild West.", a: "Margaret Hamilton" },
  { q: "There is no easy walk to freedom anywhere.", a: "Nelson Mandela" },
  { q: "Perfection is not attainable, but if we chase perfection we can catch excellence.", a: "Vince Lombardi" },
  { q: "Zazen is the dharma gate of great ease and joy.", a: "Dogen" },
  { q: "Don't play what's there, play what's not there.", a: "Miles Davis" },
  { q: "However bad life may seem, there is always something you can do and succeed at. It matters that you don't just give up.", a: "Stephen Hawking" },
  { q: "Practice means to perform, over and over again in the face of all obstacles, some act of vision.", a: "Martha Graham" },
  { q: "It is not the man who has too little, but the man who craves more, that is poor.", a: "Seneca" },
  { q: "Efficiency is doing things right; effectiveness is doing the right things.", a: "Peter Drucker" },
  { q: "Arrange whatever pieces come your way.", a: "Virginia Woolf" },
  { q: "Premature optimization is the root of all evil.", a: "Donald Knuth" },
  { q: "Nonviolence is the greatest force at the disposal of mankind.", a: "Mahatma Gandhi" },
  { q: "Leaders are made, they are not born.", a: "Vince Lombardi" },
  { q: "In the beginner's mind there are many possibilities, but in the expert's there are few.", a: "Shunryu Suzuki" },
  { q: "Man, sometimes it takes you a long time to sound like yourself.", a: "Miles Davis" },
  { q: "My expectations were reduced to zero when I was 21. Everything since then has been a bonus.", a: "Stephen Hawking" },
  { q: "We can do anything we want to do if we stick to it long enough.", a: "Helen Keller" },
  { q: "No man is free who is a slave to the body.", a: "Seneca" },
  { q: "The purpose of business is to create and keep a customer.", a: "Peter Drucker" },
  { q: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", a: "Maya Angelou" },
  { q: "Beware of bugs in the above code; I have only proved it correct, not tried it.", a: "Donald Knuth" },
  { q: "Strength does not come from physical capacity. It comes from an indomitable will.", a: "Mahatma Gandhi" },
  { q: "Everything negative - pressure, challenges - is all an opportunity for me to rise.", a: "Kobe Bryant" },
  { q: "Each of you is perfect the way you are, and you can use a little improvement.", a: "Shunryu Suzuki" },
  { q: "Not one drop of my self-worth depends on your acceptance of me.", a: "Quincy Jones" },
  { q: "A hero is an ordinary individual who finds the strength to persevere and endure in spite of overwhelming obstacles.", a: "Christopher Reeve" },
  { q: "It is my chief duty to accomplish small tasks as if they were great and noble.", a: "Helen Keller" },
  { q: "While we are postponing, life speeds by.", a: "Seneca" },
  { q: "Innovation is the specific instrument of entrepreneurship.", a: "Peter Drucker" },
  { q: "Nothing will work unless you do.", a: "Maya Angelou" },
  { q: "The best way to predict the future is to invent it.", a: "Alan Kay" },
  { q: "Truth never damages a cause that is just.", a: "Mahatma Gandhi" },
  { q: "If you're afraid to fail, then you're probably going to fail.", a: "Kobe Bryant" },
  { q: "Zen is not some kind of excitement, but concentration on our usual everyday routine.", a: "Shunryu Suzuki" },
  { q: "This will be our reply to violence: to make music more intensely, more beautifully, more devotedly than ever before.", a: "Leonard Bernstein" },
  { q: "Once you choose hope, anything's possible.", a: "Christopher Reeve" },
  { q: "A dream doesn't become reality through magic; it takes sweat, determination and hard work.", a: "Colin Powell" },
  { q: "A gem cannot be polished without friction, nor a man perfected without trials.", a: "Seneca" },
  { q: "Follow effective action with quiet reflection. From the quiet reflection will come even more effective action.", a: "Peter Drucker" },
  { q: "Try to be a rainbow in someone's cloud.", a: "Maya Angelou" },
  { q: "Simple things should be simple, complex things should be possible.", a: "Alan Kay" },
  { q: "Freedom is not worth having if it does not include the freedom to make mistakes.", a: "Mahatma Gandhi" },
  { q: "Great things come from hard work and perseverance. No excuses.", a: "Kobe Bryant" },
  { q: "The most important thing is to find out what is the most important thing.", a: "Shunryu Suzuki" },
  { q: "To be an artist means never to avert one's eyes.", a: "Akira Kurosawa" },
  { q: "What does not kill me makes me stronger.", a: "Friedrich Nietzsche" },
  { q: "Focusing is about saying no.", a: "Steve Jobs" },
  { q: "Begin at once to live, and count each separate day as a separate life.", a: "Seneca" },
  { q: "Your margin is my opportunity.", a: "Jeff Bezos" },
  { q: "You may encounter many defeats, but you must not be defeated.", a: "Maya Angelou" },
  { q: "A man who dares to waste one hour of time has not discovered the value of life.", a: "Charles Darwin" },
  { q: "You must do the things you think you cannot do.", a: "Eleanor Roosevelt" },
  { q: "The moment you give up is the moment you let someone else win.", a: "Kobe Bryant" },
  { q: "When you do something, you should burn yourself completely.", a: "Shunryu Suzuki" },
  { q: "In a mad world, only the mad are sane.", a: "Akira Kurosawa" },
  { q: "He who has a why to live for can bear almost any how.", a: "Friedrich Nietzsche" },
  { q: "Someone's sitting in the shade today because someone planted a tree a long time ago.", a: "Warren Buffett" },
  { q: "Nothing is ours except time.", a: "Seneca" },
  { q: "We are stubborn on vision. We are flexible on details.", a: "Jeff Bezos" },
  { q: "If you don't like something, change it. If you can't change it, change your attitude.", a: "Maya Angelou" },
  { q: "There is grandeur in this view of life.", a: "Charles Darwin" },
  { q: "Where, after all, do universal human rights begin? In small places, close to home.", a: "Eleanor Roosevelt" },
  { q: "Job's not finished.", a: "Kobe Bryant" },
  { q: "Smile, breathe and go slowly.", a: "Thich Nhat Hanh" },
  { q: "Drama is life with the dull bits cut out.", a: "Alfred Hitchcock" },
  { q: "The snake which cannot cast its skin has to die.", a: "Friedrich Nietzsche" },
  { q: "The difference between successful people and really successful people is that really successful people say no to almost everything.", a: "Warren Buffett" },
  { q: "Wherever there is a human being, there is an opportunity for a kindness.", a: "Seneca" },
  { q: "If you double the number of experiments you do per year, you're going to double your inventiveness.", a: "Jeff Bezos" },
  { q: "Tread softly because you tread on my dreams.", a: "William Butler Yeats" },
  { q: "The Bible shows the way to go to heaven, not the way the heavens go.", a: "Galileo Galilei" },
  { q: "Do what you feel in your heart to be right, for you'll be criticized anyway.", a: "Eleanor Roosevelt" },
  { q: "Pressure is a privilege.", a: "Billie Jean King" },
  { q: "Because you are alive, everything is possible.", a: "Thich Nhat Hanh" },
  { q: "There is no terror in the bang, only in the anticipation of it.", a: "Alfred Hitchcock" },
  { q: "Life can only be understood backwards; but it must be lived forwards.", a: "Soren Kierkegaard" },
  { q: "Almost all good writing begins with terrible first efforts. You need to start somewhere.", a: "Anne Lamott" },
  { q: "The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.", a: "Seneca" },
  { q: "In the end, we are our choices. Build yourself a great story.", a: "Jeff Bezos" },
  { q: "I have spread my dreams under your feet.", a: "William Butler Yeats" },
  { q: "I much prefer the sharpest criticism of a single intelligent man to the thoughtless approval of the masses.", a: "Johannes Kepler" },
  { q: "Courage is more exhilarating than fear and in the long run it is easier.", a: "Eleanor Roosevelt" },
  { q: "Champions keep playing until they get it right.", a: "Billie Jean King" },
  { q: "Walk as if you are kissing the Earth with your feet.", a: "Thich Nhat Hanh" },
  { q: "To make a great film you need three things: the script, the script and the script.", a: "Alfred Hitchcock" },
  { q: "Anxiety is the dizziness of freedom.", a: "Soren Kierkegaard" },
  { q: "You have to finish things - that's what you learn from.", a: "Neil Gaiman" },
  { q: "To bear trials with a calm mind robs misfortune of its strength and burden.", a: "Seneca" },
  { q: "A brand for a company is like a reputation for a person.", a: "Jeff Bezos" },
  { q: "In three words I can sum up everything I've learned about life: it goes on.", a: "Robert Frost" },
  { q: "Give me a place to stand and I will move the Earth.", a: "Archimedes" },
  { q: "The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood.", a: "Theodore Roosevelt" },
  { q: "Be bold. If you're going to make an error, make a doozy.", a: "Billie Jean King" },
  { q: "Breathing in, I calm my body. Breathing out, I smile.", a: "Thich Nhat Hanh" },
  { q: "Beauty is the mystery of life. It is not in the eye, it is in the mind.", a: "Agnes Martin" },
  { q: "To dare is to lose one's footing momentarily. Not to dare is to lose oneself.", a: "Soren Kierkegaard" },
  { q: "Once you decide on your occupation, you must immerse yourself in your work.", a: "Jiro Ono" },
  { q: "Associate with those who will make a better man of you.", a: "Seneca" },
  { q: "If you're not stubborn, you'll give up on experiments too soon.", a: "Jeff Bezos" },
  { q: "The best way out is always through.", a: "Robert Frost" },
  { q: "There is no royal road to geometry.", a: "Euclid" },
  { q: "Far better it is to dare mighty things than to take rank with those poor spirits who neither enjoy much nor suffer much.", a: "Theodore Roosevelt" },
  { q: "The last three or four reps is what makes the muscle grow.", a: "Arnold Schwarzenegger" },
  { q: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", a: "Thich Nhat Hanh" },
  { q: "I paint with my back to the world.", a: "Agnes Martin" },
  { q: "I refused to take no for an answer.", a: "Bessie Coleman" },
  { q: "Practice and all is coming.", a: "Pattabhi Jois" },
  { q: "We are more often frightened than hurt; and we suffer more from imagination than from reality.", a: "Seneca" },
  { q: "It's not an experiment if you know it's going to work.", a: "Jeff Bezos" },
  { q: "I took the one less traveled by, and that has made all the difference.", a: "Robert Frost" },
  { q: "We must know. We will know.", a: "David Hilbert" },
  { q: "Do what you can, with what you have, where you are.", a: "Theodore Roosevelt" },
  { q: "Strength does not come from winning. Your struggles develop your strengths.", a: "Arnold Schwarzenegger" },
  { q: "Peace is every step.", a: "Thich Nhat Hanh" },
  { q: "The function of art work is the stimulation of sensibilities, the renewal of memories of moments of perfection.", a: "Agnes Martin" },
  { q: "The air is the only place free from prejudices.", a: "Bessie Coleman" },
  { q: "The perfect is the enemy of the good.", a: "Voltaire" },
  { q: "Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it.", a: "Seneca" },
  { q: "Invention requires a long-term willingness to be misunderstood.", a: "Jeff Bezos" },
  { q: "Freedom lies in being bold.", a: "Robert Frost" },
  { q: "Mathematics is the queen of the sciences.", a: "Carl Friedrich Gauss" },
  { q: "Speak softly and carry a big stick; you will go far.", a: "Theodore Roosevelt" },
  { q: "The mind is the limit. As long as the mind can envision it, you can do it.", a: "Arnold Schwarzenegger" },
  { q: "Be kind whenever possible. It is always possible.", a: "Dalai Lama" },
  { q: "You don't take a photograph, you make it.", a: "Ansel Adams" },
  { q: "My doctors told me I would never walk again. My mother told me I would. I believed my mother.", a: "Wilma Rudolph" },
  { q: "All of humanity's problems stem from man's inability to sit quietly in a room alone.", a: "Blaise Pascal" },
  { q: "If a man knows not to which port he sails, no wind is favorable.", a: "Seneca" },
  { q: "Innovation distinguishes between a leader and a follower.", a: "Steve Jobs" },
  { q: "Hope is the thing with feathers that perches in the soul.", a: "Emily Dickinson" },
  { q: "It is through science that we prove, but through intuition that we discover.", a: "Henri Poincare" },
  { q: "Nine-tenths of wisdom is being wise in time.", a: "Theodore Roosevelt" },
  { q: "Don't be too proud to take lessons. I'm not.", a: "Jack Nicklaus" },
  { q: "My religion is very simple. My religion is kindness.", a: "Dalai Lama" },
  { q: "There are always two people in every picture: the photographer and the viewer.", a: "Ansel Adams" },
  { q: "The triumph can't be had without the struggle.", a: "Wilma Rudolph" },
  { q: "Attention is the rarest and purest form of generosity.", a: "Simone Weil" },
  { q: "The whole future lies in uncertainty: live immediately.", a: "Seneca" },
  { q: "Your time is limited, so don't waste it living someone else's life.", a: "Steve Jobs" },
  { q: "I dwell in Possibility, a fairer House than Prose.", a: "Emily Dickinson" },
  { q: "A mathematician, like a painter or a poet, is a maker of patterns.", a: "G. H. Hardy" },
  { q: "No man is justified in doing evil on the ground of expediency.", a: "Theodore Roosevelt" },
  { q: "Concentration is a fine antidote to anxiety.", a: "Jack Nicklaus" },
  { q: "If you can, help others; if you cannot do that, at least do not harm them.", a: "Dalai Lama" },
  { q: "A good photograph is knowing where to stand.", a: "Ansel Adams" },
  { q: "I am different, not less.", a: "Temple Grandin" },
  { q: "Attention is the beginning of devotion.", a: "Mary Oliver" },
  { q: "Throw me to the wolves and I will return leading the pack.", a: "Seneca" },
  { q: "Stay hungry. Stay foolish.", a: "Steve Jobs" },
  { q: "If I can stop one heart from breaking, I shall not live in vain.", a: "Emily Dickinson" },
  { q: "Beauty is the first test: there is no permanent place in the world for ugly mathematics.", a: "G. H. Hardy" },
  { q: "Character, in the long run, is the decisive factor in the life of an individual and of nations alike.", a: "Theodore Roosevelt" },
  { q: "Resolve never to quit, never to give up, no matter what the situation.", a: "Jack Nicklaus" },
  { q: "Happiness is not something ready made. It comes from your own actions.", a: "Dalai Lama" },
  { q: "Twelve significant photographs in any one year is a good crop.", a: "Ansel Adams" },
  { q: "The world needs all kinds of minds.", a: "Temple Grandin" },
  { q: "Success is the sum of small efforts repeated day in and day out.", a: "Robert Collier" },
  { q: "It is not the man who has too little who is poor, but the one who hankers after more.", a: "Seneca" },
  { q: "Design is not just what it looks like and feels like. Design is how it works.", a: "Steve Jobs" },
  { q: "Forever is composed of nows.", a: "Emily Dickinson" },
  { q: "Science and everyday life cannot and should not be separated.", a: "Rosalind Franklin" },
  { q: "If there is no struggle, there is no progress.", a: "Frederick Douglass" },
  { q: "If you no longer go for a gap that exists, you are no longer a racing driver.", a: "Ayrton Senna" },
  { q: "Silence is sometimes the best answer.", a: "Dalai Lama" },
  { q: "Art is the only way to run away without leaving home.", a: "Twyla Tharp" },
  { q: "I cannot pretend I am without fear. But my predominant feeling is one of gratitude.", a: "Oliver Sacks" },
  { q: "There are no shortcuts to any place worth going.", a: "Beverly Sills" },
  { q: "Men do not care how nobly they live, but only how long, although it is within the reach of every man to live nobly.", a: "Seneca" },
  { q: "Deciding what not to do is as important as deciding what to do.", a: "Steve Jobs" },
  { q: "Not knowing when the dawn will come, I open every door.", a: "Emily Dickinson" },
  { q: "The purpose of computing is insight, not numbers.", a: "Richard Hamming" },
  { q: "Power concedes nothing without a demand. It never did and it never will.", a: "Frederick Douglass" },
  { q: "Being second is to be the first of the ones who lose.", a: "Ayrton Senna" },
  { q: "Trying to define yourself is like trying to bite your own teeth.", a: "Alan Watts" },
  { q: "Creativity is an act of defiance.", a: "Twyla Tharp" },
  { q: "The ultimate measure of a man is where he stands at times of challenge and controversy.", a: "Martin Luther King Jr." },
  { q: "Seize the day, trusting as little as possible in the future.", a: "Horace" },
  { q: "It's not what happens to you, but how you react to it that matters.", a: "Epictetus" },
  { q: "It doesn't make sense to hire smart people and tell them what to do.", a: "Steve Jobs" },
  { q: "In the depth of winter, I finally learned that within me there lay an invincible summer.", a: "Albert Camus" },
  { q: "Simplicity is prerequisite for reliability.", a: "Edsger Dijkstra" },
  { q: "I would unite with anybody to do right and with nobody to do wrong.", a: "Frederick Douglass" },
  { q: "I am not designed to come second or third. I am designed to win.", a: "Ayrton Senna" },
  { q: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", a: "Alan Watts" },
  { q: "In order to be creative you have to know how to prepare to be creative.", a: "Twyla Tharp" },
  { q: "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but keep moving forward.", a: "Martin Luther King Jr." },
  { q: "If you add a little to a little, and do this often, soon the little will become great.", a: "Hesiod" },
  { q: "Men are disturbed not by things, but by the views which they take of things.", a: "Epictetus" },
  { q: "Quality is more important than quantity. One home run is much better than two doubles.", a: "Steve Jobs" },
  { q: "Real generosity toward the future lies in giving all to the present.", a: "Albert Camus" },
  { q: "The question of whether machines can think is about as relevant as the question of whether submarines can swim.", a: "Edsger Dijkstra" },
  { q: "The limits of tyrants are prescribed by the endurance of those whom they oppress.", a: "Frederick Douglass" },
  { q: "Gold medals aren't really made of gold. They're made of sweat, determination, and a hard-to-find alloy called guts.", a: "Dan Gable" },
  { q: "Muddy water is best cleared by leaving it alone.", a: "Alan Watts" },
  { q: "Nobody tells this to people who are beginners, and I really wish somebody had told this to me.", a: "Ira Glass" },
  { q: "Only when it is dark enough can you see the stars.", a: "Martin Luther King Jr." },
  { q: "Attempt easy tasks as if they were difficult, and difficult as if they were easy.", a: "Baltasar Gracian" },
  { q: "No man is free who is not master of himself.", a: "Epictetus" },
  { q: "You can't connect the dots looking forward; you can only connect them looking backwards.", a: "Steve Jobs" },
  { q: "Autumn is a second spring when every leaf is a flower.", a: "Albert Camus" },
  { q: "Nothing is too wonderful to be true, if it be consistent with the laws of nature.", a: "Michael Faraday" },
  { q: "I prayed for freedom for twenty years, but received no answer until I prayed with my legs.", a: "Frederick Douglass" },
  { q: "Once you've wrestled, everything else in life is easy.", a: "Dan Gable" },
  { q: "No valid plans for the future can be made by those who have no capacity for living now.", a: "Alan Watts" },
  { q: "The most important possible thing you can do is do a lot of work.", a: "Ira Glass" },
  { q: "I have learned over the years that when one's mind is made up, this diminishes fear.", a: "Rosa Parks" },
  { q: "Practice isn't the thing you do once you're good. It's the thing you do that makes you good.", a: "Malcolm Gladwell" },
  { q: "We have two ears and one mouth so that we can listen twice as much as we speak.", a: "Epictetus" },
  { q: "I'm as proud of many of the things we haven't done as the things we have done.", a: "Steve Jobs" },
  { q: "One must imagine Sisyphus happy.", a: "Albert Camus" },
  { q: "The best way to have a good idea is to have a lot of ideas.", a: "Linus Pauling" },
  { q: "Ask not what your country can do for you, ask what you can do for your country.", a: "John F Kennedy" },
  { q: "You miss 100 percent of the shots you don't take.", a: "Wayne Gretzky" },
  { q: "Be here now.", a: "Ram Dass" },
  { q: "It is only by going through a volume of work that your work will be as good as your ambitions.", a: "Ira Glass" },
  { q: "You must never be fearful about what you are doing when it is right.", a: "Rosa Parks" },
  { q: "Satisfaction lies in the effort, not in the attainment. Full effort is full victory.", a: "Mahatma Gandhi" },
  { q: "First say to yourself what you would be; and then do what you have to do.", a: "Epictetus" },
  { q: "Coming together is a beginning; keeping together is progress; working together is success.", a: "Henry Ford" },
  { q: "Live to the point of tears.", a: "Albert Camus" },
  { q: "Science cannot solve the ultimate mystery of nature.", a: "Max Planck" },
  { q: "Let us never negotiate out of fear. But let us never fear to negotiate.", a: "John F Kennedy" },
  { q: "It ain't over till it's over.", a: "Yogi Berra" },
  { q: "We are all just walking each other home.", a: "Ram Dass" },
  { q: "Simplicity is not the absence of clutter; that's a consequence of simplicity.", a: "Jony Ive" },
  { q: "Never, ever be afraid to make some noise and get in good trouble, necessary trouble.", a: "John Lewis" },
  { q: "There is only one way to eat an elephant: a bite at a time.", a: "Desmond Tutu" },
  { q: "Wealth consists not in having great possessions, but in having few wants.", a: "Epictetus" },
  { q: "Whether you think you can, or you think you can't, you're right.", a: "Henry Ford" },
  { q: "A book must be the axe for the frozen sea within us.", a: "Franz Kafka" },
  { q: "An expert is a person who has made all the mistakes that can be made in a very narrow field.", a: "Niels Bohr" },
  { q: "The rights of every man are diminished when the rights of one man are threatened.", a: "John F Kennedy" },
  { q: "Baseball is ninety percent mental and the other half is physical.", a: "Yogi Berra" },
  { q: "The quieter you become, the more you can hear.", a: "Ram Dass" },
  { q: "Our goal is to try to bring a calm and simplicity to what are incredibly complex problems.", a: "Jony Ive" },
  { q: "I just wish people would realize that anything's possible if you try.", a: "Terry Fox" },
  { q: "A wealth of information creates a poverty of attention.", a: "Herbert Simon" },
  { q: "It is impossible for a man to learn what he thinks he already knows.", a: "Epictetus" },
  { q: "Failure is simply the opportunity to begin again, this time more intelligently.", a: "Henry Ford" },
  { q: "Anyone who keeps the ability to see beauty never grows old.", a: "Franz Kafka" },
  { q: "What we observe is not nature itself, but nature exposed to our method of questioning.", a: "Werner Heisenberg" },
  { q: "We choose to go to the moon in this decade and do the other things, not because they are easy, but because they are hard.", a: "John F Kennedy" },
  { q: "Success is no accident. It is hard work, perseverance, sacrifice and most of all, love of what you are doing.", a: "Pele" },
  { q: "The heart surrenders everything to the moment. The mind judges and holds back.", a: "Ram Dass" },
  { q: "Simplicity is the keynote of all true elegance.", a: "Coco Chanel" },
  { q: "Bless you, prison, for having been in my life.", a: "Aleksandr Solzhenitsyn" },
  { q: "Seek not that the things which happen should happen as you wish; but wish the things which happen to be as they are.", a: "Epictetus" },
  { q: "Quality means doing it right when no one is looking.", a: "Henry Ford" },
  { q: "You do not need to leave your room. Remain sitting at your table and listen.", a: "Franz Kafka" },
  { q: "The true logic of this world is in the calculus of probabilities.", a: "James Clerk Maxwell" },
  { q: "Efforts and courage are not enough without purpose and direction.", a: "John F Kennedy" },
  { q: "Awards become corroded, friends gather no dust.", a: "Jesse Owens" },
  { q: "Do nothing which is of no use.", a: "Miyamoto Musashi" },
  { q: "In order to be irreplaceable one must always be different.", a: "Coco Chanel" },
  { q: "Feet, what do I need them for if I have wings to fly?", a: "Frida Kahlo" },
  { q: "Don't explain your philosophy. Embody it.", a: "Epictetus" },
  { q: "A business that makes nothing but money is a poor kind of business.", a: "Henry Ford" },
  { q: "I have always imagined that Paradise will be a kind of library.", a: "Jorge Luis Borges" },
  { q: "Equipped with his five senses, man explores the universe around him and calls the adventure Science.", a: "Edwin Hubble" },
  { q: "A man does what he must in spite of personal consequences, and that is the basis of all human morality.", a: "John F Kennedy" },
  { q: "It is better to look ahead and prepare than to look back and regret.", a: "Jackie Joyner-Kersee" },
  { q: "Accept everything just the way it is.", a: "Miyamoto Musashi" },
  { q: "Fashion changes, but style endures.", a: "Coco Chanel" },
  { q: "I will seize fate by the throat; it shall certainly never wholly overcome me.", a: "Ludwig van Beethoven" },
  { q: "Difficulties are things that show a person what they are.", a: "Epictetus" },
  { q: "Anyone who stops learning is old, whether at twenty or eighty.", a: "Henry Ford" },
  { q: "Writing is nothing more than a guided dream.", a: "Jorge Luis Borges" },
  { q: "Like what you do, and then you will do your best.", a: "Katherine Johnson" },
  { q: "Change is the law of life. And those who look only to the past or present are certain to miss the future.", a: "John F Kennedy" },
  { q: "You can't put a limit on anything. The more you dream, the farther you get.", a: "Michael Phelps" },
  { q: "Do not regret what you have done.", a: "Miyamoto Musashi" },
  { q: "Space and light and order. Those are the things that men need just as much as they need bread or a place to sleep.", a: "Le Corbusier" },
  { q: "Life is not easy for any of us. But what of that? We must have perseverance and confidence in ourselves.", a: "Marie Curie" },
  { q: "Any person capable of angering you becomes your master.", a: "Epictetus" },
  { q: "You cannot push anyone up the ladder unless he is willing to climb himself.", a: "Andrew Carnegie" },
  { q: "Let others pride themselves about how many pages they have written; I'd rather boast about the ones I've read.", a: "Jorge Luis Borges" },
  { q: "The good thing about science is that it's true whether or not you believe in it.", a: "Neil deGrasse Tyson" },
  { q: "If you are neutral in situations of injustice, you have chosen the side of the oppressor.", a: "Desmond Tutu" },
  { q: "Worrying gets you nowhere. If you turn up worrying about how you're going to perform, you've already lost.", a: "Usain Bolt" },
  { q: "Think lightly of yourself and deeply of the world.", a: "Miyamoto Musashi" },
  { q: "A house is a machine for living in.", a: "Le Corbusier" },
  { q: "Never give in, never, never, never.", a: "Winston Churchill" },
  { q: "If you wish to improve, be content to be thought foolish and stupid.", a: "Epictetus" },
  { q: "The man who dies rich, dies disgraced.", a: "Andrew Carnegie" },
  { q: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.", a: "Toni Morrison" },
  { q: "The reward for work well done is the opportunity to do more.", a: "Jonas Salk" },
  { q: "Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.", a: "Desmond Tutu" },
  { q: "No matter how good you get you can always get better, and that's the exciting part.", a: "Tiger Woods" },
  { q: "Perceive that which cannot be seen with the eye.", a: "Miyamoto Musashi" },
  { q: "Architecture is the learned game, correct and magnificent, of forms assembled in the light.", a: "Le Corbusier" },
  { q: "Courage is the price that life exacts for granting peace.", a: "Amelia Earhart" },
  { q: "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.", a: "Epictetus" },
  { q: "Put all your eggs in one basket, and then watch that basket.", a: "Andrew Carnegie" },
  { q: "You are your best thing.", a: "Toni Morrison" },
  { q: "The Earth is the cradle of humanity, but one cannot live in a cradle forever.", a: "Konstantin Tsiolkovsky" },
  { q: "Hope is being able to see that there is light despite all of the darkness.", a: "Desmond Tutu" },
  { q: "There is no way around the hard work. Embrace it.", a: "Roger Federer" },
  { q: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", a: "Rumi" },
  { q: "Form and function should be one, joined in a spiritual union.", a: "Frank Lloyd Wright" },
  { q: "The most difficult thing is the decision to act, the rest is merely tenacity.", a: "Amelia Earhart" },
  { q: "Only the educated are free.", a: "Epictetus" },
  { q: "Teamwork is the ability to work together toward a common vision.", a: "Andrew Carnegie" },
  { q: "If you surrender to the air, you can ride it.", a: "Toni Morrison" },
  { q: "Scientists discover the world that exists; engineers create the world that never was.", a: "Theodore von Karman" },
  { q: "My humanity is bound up in yours, for we can only be human together.", a: "Desmond Tutu" },
  { q: "Losing is not my enemy. Fear of losing is my enemy.", a: "Rafael Nadal" },
  { q: "Out beyond ideas of wrongdoing and rightdoing, there is a field. I will meet you there.", a: "Rumi" },
  { q: "Study nature, love nature, stay close to nature. It will never fail you.", a: "Frank Lloyd Wright" },
  { q: "I am deliberate and afraid of nothing.", a: "Audre Lorde" },
  { q: "Make the best use of what is in your power, and take the rest as it happens.", a: "Epictetus" },
  { q: "Pain plus reflection equals progress.", a: "Ray Dalio" },
  { q: "The function of freedom is to free someone else.", a: "Toni Morrison" },
  { q: "I just wondered how things were put together.", a: "Claude Shannon" },
  { q: "Get in good trouble, necessary trouble, and help redeem the soul of America.", a: "John Lewis" },
  { q: "Start where you are. Use what you have. Do what you can.", a: "Arthur Ashe" },
  { q: "What you seek is seeking you.", a: "Rumi" },
  { q: "An idea is salvation by imagination.", a: "Frank Lloyd Wright" },
  { q: "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", a: "Epictetus" },
  { q: "He who lives by the crystal ball will eat shattered glass.", a: "Ray Dalio" },
  { q: "Not everything that is faced can be changed, but nothing can be changed until it is faced.", a: "James Baldwin" },
  { q: "A problem well stated is a problem half solved.", a: "Charles Kettering" },
  { q: "Freedom is not a state; it is an act.", a: "John Lewis" },
  { q: "Success is a journey, not a destination. The doing is often more important than the outcome.", a: "Arthur Ashe" },
  { q: "In the midst of chaos, there is also opportunity.", a: "Sun Tzu" },
  { q: "Art is not what you see, but what you make others see.", a: "Edgar Degas" },
  { q: "Know, first, who you are, and then adorn yourself accordingly.", a: "Epictetus" },
  { q: "Truth is the essential foundation for producing good outcomes.", a: "Ray Dalio" },
  { q: "The place in which I'll fit will not exist until I make it.", a: "James Baldwin" },
  { q: "It is possible to fly without motors, but not without knowledge and skill.", a: "Wilbur Wright" },
  { q: "Do not get lost in a sea of despair. Be hopeful, be optimistic.", a: "John Lewis" },
  { q: "Never underestimate the power of dreams and the influence of the human spirit.", a: "Wilma Rudolph" },
  { q: "If you know the enemy and know yourself, you need not fear the result of a hundred battles.", a: "Sun Tzu" },
  { q: "Art does not reproduce the visible; rather, it makes visible.", a: "Paul Klee" },
  { q: "Practice yourself, for heaven's sake, in little things; and thence proceed to greater.", a: "Epictetus" },
  { q: "Don't let fears of what others think of you stand in your way.", a: "Ray Dalio" },
  { q: "You think your pain and your heartbreak are unprecedented in the history of the world, but then you read.", a: "James Baldwin" },
  { q: "All science is either physics or stamp collecting.", a: "Ernest Rutherford" },
  { q: "When you see something that is not right, you must say something. You must do something.", a: "John Lewis" },
  { q: "Winning is great, but if you are really going to do something in life, the secret is learning how to lose.", a: "Wilma Rudolph" },
  { q: "The supreme art of war is to subdue the enemy without fighting.", a: "Sun Tzu" },
  { q: "Color is the keyboard, the eyes are the hammers, the soul is the piano with many strings.", a: "Wassily Kandinsky" },
  { q: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", a: "Aristotle" },
  { q: "Seek out the smartest people who disagree with you and try to understand their reasoning.", a: "Ray Dalio" },
  { q: "Love takes off the masks that we fear we cannot live without and know we cannot live within.", a: "James Baldwin" },
  { q: "Great discoveries and improvements invariably involve the cooperation of many minds.", a: "Alexander Graham Bell" },
  { q: "Fight for the things that you care about, but do it in a way that will lead others to join you.", a: "Ruth Bader Ginsburg" },
  { q: "I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", a: "Bruce Lee" },
  { q: "Victorious warriors win first and then go to war.", a: "Sun Tzu" },
  { q: "Have no fear of perfection, you'll never reach it.", a: "Salvador Dali" },
  { q: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", a: "Aristotle" },
  { q: "Play long term games with long term people.", a: "Naval Ravikant" },
  { q: "The wound is the place where the Light enters you.", a: "Rumi" },
  { q: "All creative people want to do the unexpected.", a: "Hedy Lamarr" },
  { q: "Women belong in all places where decisions are being made.", a: "Ruth Bader Ginsburg" },
  { q: "Do not pray for an easy life, pray for the strength to endure a difficult one.", a: "Bruce Lee" },
  { q: "He who knows when he can fight and when he cannot will be victorious.", a: "Sun Tzu" },
  { q: "They always say time changes things, but you actually have to change them yourself.", a: "Andy Warhol" },
  { q: "Happiness depends upon ourselves.", a: "Aristotle" },
  { q: "Seek wealth, not money or status.", a: "Naval Ravikant" },
  { q: "Let yourself be silently drawn by the strange pull of what you really love.", a: "Rumi" },
  { q: "Don't let anyone keep you down for silly reasons such as who you are.", a: "Vera Rubin" },
  { q: "Real change, enduring change, happens one step at a time.", a: "Ruth Bader Ginsburg" },
  { q: "Celebrate what you've accomplished, but raise the bar a little higher each time you succeed.", a: "Mia Hamm" },
  { q: "Do not seek to follow in the footsteps of the wise. Seek what they sought.", a: "Basho" },
  { q: "Art is a guarantee of sanity.", a: "Louise Bourgeois" },
  { q: "The roots of education are bitter, but the fruit is sweet.", a: "Aristotle" },
  { q: "You're not going to get rich renting out your time.", a: "Naval Ravikant" },
  { q: "Sell your cleverness and buy bewilderment.", a: "Rumi" },
  { q: "Science progresses best when observations force us to alter our preconceptions.", a: "Vera Rubin" },
  { q: "Dissents speak to a future age.", a: "Ruth Bader Ginsburg" },
  { q: "Motivation is what gets you started. Habit is what keeps you going.", a: "Jim Ryun" },
  { q: "An old pond; a frog jumps in, the sound of water.", a: "Basho" },
  { q: "If I could say it in words there would be no reason to paint.", a: "Edward Hopper" },
  { q: "Knowing yourself is the beginning of all wisdom.", a: "Aristotle" },
  { q: "Learn to sell. Learn to build. If you can do both, you will be unstoppable.", a: "Naval Ravikant" },
  { q: "You were born with wings, why prefer to crawl through life?", a: "Rumi" },
  { q: "I do not fear computers. I fear the lack of them.", a: "Isaac Asimov" },
  { q: "Hope is a state of mind, not a state of the world.", a: "Vaclav Havel" },
  { q: "You have to forget your last marathon before you try another.", a: "Frank Shorter" },
  { q: "It is no measure of health to be well adjusted to a profoundly sick society.", a: "Jiddu Krishnamurti" },
  { q: "Make visible what, without you, might perhaps never have been seen.", a: "Robert Bresson" },
  { q: "Courage is the first of human qualities because it is the quality which guarantees the others.", a: "Aristotle" },
  { q: "Earn with your mind, not your time.", a: "Naval Ravikant" },
  { q: "Knowing is not enough; we must apply. Willing is not enough; we must do.", a: "Johann Wolfgang von Goethe" },
  { q: "If you were plowing a field, which would you rather use: two strong oxen or 1024 chickens?", a: "Seymour Cray" },
  { q: "Truth and love must prevail over lies and hatred.", a: "Vaclav Havel" },
  { q: "The will to win means nothing without the will to prepare.", a: "Juma Ikangaa" },
  { q: "The ability to observe without evaluating is the highest form of intelligence.", a: "Jiddu Krishnamurti" },
  { q: "The enemy of art is the absence of limitations.", a: "Orson Welles" },
  { q: "No great mind has ever existed without a touch of madness.", a: "Aristotle" },
  { q: "Make luck your destiny by becoming the best at what you do.", a: "Naval Ravikant" },
  { q: "Treat people as if they were what they ought to be and you help them become what they are capable of being.", a: "Johann Wolfgang von Goethe" },
  { q: "Talk is cheap. Show me the code.", a: "Linus Torvalds" },
  { q: "Keep the company of those who seek the truth; run from those who have found it.", a: "Vaclav Havel" },
  { q: "It's not the will to win that matters. It's the will to prepare to win that matters.", a: "Bear Bryant" },
  { q: "Truth is a pathless land.", a: "Jiddu Krishnamurti" },
  { q: "Cinema is a matter of what's in the frame and what's out.", a: "Martin Scorsese" },
  { q: "Character is that which reveals moral purpose.", a: "Aristotle" },
  { q: "Make something people want.", a: "Paul Graham" },
  { q: "A man sees in the world what he carries in his heart.", a: "Johann Wolfgang von Goethe" },
  { q: "Adding manpower to a late software project makes it later.", a: "Fred Brooks" },
  { q: "Trust yourself. Create the kind of self that you will be happy to live with all your life.", a: "Golda Meir" },
  { q: "It never gets easier, you just go faster.", a: "Greg LeMond" },
  { q: "The observer is the observed.", a: "Jiddu Krishnamurti" },
  { q: "If you have a problem with the third act, the real problem is in the first act.", a: "Billy Wilder" },
  { q: "Hope is a waking dream.", a: "Aristotle" },
  { q: "Startups take off because the founders make them take off.", a: "Paul Graham" },
  { q: "We are all in the gutter, but some of us are looking at the stars.", a: "Oscar Wilde" },
  { q: "It is difficult to say what is impossible, for the dream of yesterday is the hope of today and the reality of tomorrow.", a: "Robert Goddard" },
  { q: "A leader who doesn't hesitate before he sends his nation into battle is not fit to be a leader.", a: "Golda Meir" },
  { q: "Ride as much or as little, as long or as short as you feel. But ride.", a: "Eddy Merckx" },
  { q: "There are two kinds of music. Good music, and the other kind.", a: "Duke Ellington" },
  { q: "The whole is greater than the sum of its parts.", a: "Aristotle" },
  { q: "Do things that don't scale.", a: "Paul Graham" },
  { q: "To live is the rarest thing in the world. Most people exist, that is all.", a: "Oscar Wilde" },
  { q: "Science is a very human form of knowledge.", a: "Jacob Bronowski" },
  { q: "One cannot and must not try to erase the past merely because it does not fit the present.", a: "Golda Meir" },
  { q: "Everyone has a plan until they get punched in the mouth.", a: "Mike Tyson" },
  { q: "The piano ain't got no wrong notes.", a: "Thelonious Monk" },
  { q: "No man can live happily who regards himself alone, who turns everything to his own advantage.", a: "Seneca" },
  { q: "A startup is a company designed to grow fast.", a: "Paul Graham" },
  { q: "Tell me, what is it you plan to do with your one wild and precious life?", a: "Mary Oliver" },
  { q: "A language that doesn't affect the way you think about programming is not worth knowing.", a: "Alan Perlis" },
  { q: "Difficulties are just things to overcome, after all.", a: "Ernest Shackleton" },
  { q: "A champion is someone who gets up when he can't.", a: "Jack Dempsey" },
  { q: "The more constraints one imposes, the more one frees oneself.", a: "Igor Stravinsky" },
  { q: "Everything flows and nothing stays.", a: "Heraclitus" },
  { q: "The most important thing is to be relentlessly resourceful.", a: "Paul Graham" },
  { q: "Instructions for living a life: Pay attention. Be astonished. Tell about it.", a: "Mary Oliver" },
  { q: "Optimism is true moral courage.", a: "Ernest Shackleton" },
  { q: "You can't win unless you learn how to lose.", a: "Kareem Abdul-Jabbar" },
  { q: "An artist's duty, as far as I'm concerned, is to reflect the times.", a: "Nina Simone" },
  { q: "No man ever steps in the same river twice.", a: "Heraclitus" },
  { q: "It's better to have 100 people love you than a million people sort of like you.", a: "Paul Graham" },
  { q: "You do not have to be good.", a: "Mary Oliver" },
  { q: "Superhuman effort isn't worth a damn unless it achieves results.", a: "Ernest Shackleton" },
  { q: "The chicken is involved; the pig is committed. That's the difference between involvement and commitment.", a: "Martina Navratilova" },
  { q: "The life of a designer is a life of fight against the ugliness.", a: "Massimo Vignelli" },
  { q: "Character is destiny.", a: "Heraclitus" },
  { q: "High margins tend to make companies lazy.", a: "Sam Walton" },
  { q: "Walk on air against your better judgement.", a: "Seamus Heaney" },
  { q: "Up, you mighty race, accomplish what you will.", a: "Marcus Garvey" },
  { q: "I'd rather regret the risks that didn't work out than the chances I didn't take at all.", a: "Simone Biles" },
  { q: "Design is the method of putting form and content together.", a: "Paul Rand" },
  { q: "Big results require big ambitions.", a: "Heraclitus" },
  { q: "There is only one boss. The customer.", a: "Sam Walton" },
  { q: "If you have the words, there's always a chance that you'll find the way.", a: "Seamus Heaney" },
  { q: "A people without the knowledge of their past history, origin and culture is like a tree without roots.", a: "Marcus Garvey" },
  { q: "If everything seems under control, you're not going fast enough.", a: "Mario Andretti" },
  { q: "Design is thinking made visual.", a: "Saul Bass" },
  { q: "The sun is new each day.", a: "Heraclitus" },
  { q: "Celebrate your successes. Find some humor in your failures.", a: "Sam Walton" },
  { q: "You can cut all the flowers but you cannot keep spring from coming.", a: "Pablo Neruda" },
  { q: "If you have no confidence in self, you are twice defeated in the race of life.", a: "Marcus Garvey" },
  { q: "Mind is everything; muscle, mere pieces of rubber. All that I am, I am because of my mind.", a: "Paavo Nurmi" },
  { q: "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.", a: "Antoine de Saint-Exupery" },
  { q: "Much learning does not teach understanding.", a: "Heraclitus" },
  { q: "Swim upstream. Go the other way. Ignore the conventional wisdom.", a: "Sam Walton" },
  { q: "Not all those who wander are lost.", a: "J. R. R. Tolkien" },
  { q: "Liberate the minds of men and ultimately you will liberate the bodies of men.", a: "Marcus Garvey" },
  { q: "Don't give up. Don't ever give up.", a: "Jim Valvano" },
  { q: "God is in the details.", a: "Ludwig Mies van der Rohe" },
  { q: "The unexamined life is not worth living.", a: "Plato" },
  { q: "An entrepreneur is someone who jumps off a cliff and builds a plane on the way down.", a: "Reid Hoffman" },
  { q: "It is good to have an end to journey toward; but it is the journey that matters, in the end.", a: "Ursula K. Le Guin" },
  { q: "We must always take sides. Neutrality helps the oppressor, never the victim.", a: "Elie Wiesel" },
  { q: "The difference between the impossible and the possible lies in a person's determination.", a: "Tommy Lasorda" },
  { q: "There are 360 degrees, so why stick to one?", a: "Zaha Hadid" },
  { q: "The beginning is the most important part of the work.", a: "Plato" },
  { q: "If you are not embarrassed by the first version of your product, you've launched too late.", a: "Reid Hoffman" },
  { q: "Love does not just sit there, like a stone; it has to be made, like bread.", a: "Ursula K. Le Guin" },
  { q: "The opposite of love is not hate, it's indifference.", a: "Elie Wiesel" },
  { q: "There may be people that have more talent than you, but there's no excuse for anyone to work harder than you.", a: "Derek Jeter" },
  { q: "Making the simple complicated is commonplace; making the complicated simple, awesomely simple, that's creativity.", a: "Charles Mingus" },
  { q: "Courage is knowing what not to fear.", a: "Plato" },
  { q: "No matter how brilliant your mind or strategy, if you're playing a solo game, you'll always lose out to a team.", a: "Reid Hoffman" },
  { q: "Work is love made visible.", a: "Kahlil Gibran" },
  { q: "Only those who dare to fail greatly can ever achieve greatly.", a: "Robert F Kennedy" },
  { q: "My motto was always to keep swinging.", a: "Hank Aaron" },
  { q: "The body says what words cannot.", a: "Martha Graham" },
  { q: "Ignorance, the root and stem of every evil.", a: "Plato" },
  { q: "Being contrarian and right is how you generate outsized returns.", a: "Howard Marks" },
  { q: "Beauty is eternity gazing at itself in a mirror.", a: "Kahlil Gibran" },
  { q: "Few are willing to brave the disapproval of their fellows, the censure of their colleagues, the wrath of their society.", a: "Robert F Kennedy" },
  { q: "Playing football is very simple, but playing simple football is the hardest thing there is.", a: "Johan Cruyff" },
  { q: "I do not try to dance better than anyone else. I only try to dance better than myself.", a: "Mikhail Baryshnikov" },
  { q: "Wise men speak because they have something to say; fools because they have to say something.", a: "Plato" },
  { q: "You can't predict. You can prepare.", a: "Howard Marks" },
  { q: "And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom.", a: "Anais Nin" },
  { q: "These are the times that try men's souls.", a: "Thomas Paine" },
  { q: "You have to fight to reach your dream. You have to sacrifice and work hard for it.", a: "Lionel Messi" },
  { q: "You can't use up creativity. The more you use, the more you have.", a: "Maya Angelou" },
  { q: "Good actions give strength to ourselves and inspire good actions in others.", a: "Plato" },
  { q: "Risk means more things can happen than will happen.", a: "Howard Marks" },
  { q: "We write to taste life twice, in the moment and in retrospection.", a: "Anais Nin" },
  { q: "Tyranny, like hell, is not easily conquered.", a: "Thomas Paine" },
  { q: "Excellence is the gradual result of always striving to do better.", a: "Pat Riley" },
  { q: "Every good painter paints what he is.", a: "Jackson Pollock" },
  { q: "A life without books is a body without a soul.", a: "Cicero" },
  { q: "The riskiest thing in the world is the belief that there's no risk.", a: "Howard Marks" },
  { q: "I took a deep breath and listened to the old brag of my heart. I am, I am, I am.", a: "Sylvia Plath" },
  { q: "If they don't give you a seat at the table, bring a folding chair.", a: "Shirley Chisholm" },
  { q: "I've got a theory that if you give 100 percent all of the time, somehow things will work out in the end.", a: "Larry Bird" },
  { q: "While there's life, there's hope.", a: "Cicero" },
  { q: "Take care of the people, the products, and the profits, in that order.", a: "Ben Horowitz" },
  { q: "Faith is the bird that feels the light when the dawn is still dark.", a: "Rabindranath Tagore" },
  { q: "What the people want is very simple. They want an America as good as its promise.", a: "Barbara Jordan" },
  { q: "Ask not what your teammates can do for you. Ask what you can do for your teammates.", a: "Magic Johnson" },
  { q: "Gratitude is not only the greatest of virtues, but the parent of all others.", a: "Cicero" },
  { q: "The hard thing isn't setting a big, hairy, audacious goal. The hard thing is laying people off when you miss it.", a: "Ben Horowitz" },
  { q: "Let me not pray to be sheltered from dangers but to be fearless in facing them.", a: "Rabindranath Tagore" },
  { q: "Failure is impossible.", a: "Susan B Anthony" },
  { q: "Don't look back. Something might be gaining on you.", a: "Satchel Paige" },
  { q: "The life of the dead is placed in the memory of the living.", a: "Cicero" },
  { q: "There are no silver bullets, only lead bullets.", a: "Ben Horowitz" },
  { q: "Even the darkest night will end and the sun will rise.", a: "Victor Hugo" },
  { q: "Never measure the height of a mountain until you have reached the top.", a: "Dag Hammarskjold" },
  { q: "A life is not important except in the impact it has on other lives.", a: "Jackie Robinson" },
  { q: "Any man can make mistakes, but only an idiot persists in his error.", a: "Cicero" },
  { q: "Good is the enemy of great.", a: "Jim Collins" },
  { q: "It is better to fail in originality than to succeed in imitation.", a: "Herman Melville" },
  { q: "If you don't believe in yourself, why is anyone else going to believe in you?", a: "Tom Brady" },
  { q: "Nobody can give you wiser advice than yourself.", a: "Cicero" },
  { q: "First who, then what. Get the right people on the bus.", a: "Jim Collins" },
  { q: "I am not afraid of storms, for I am learning how to sail my ship.", a: "Louisa May Alcott" },
  { q: "What I do is prepare myself until I know I can do what I have to do.", a: "Joe Namath" },
  { q: "Friendship improves happiness and abates misery, by the doubling of our joy and the dividing of our grief.", a: "Cicero" },
  { q: "Greatness is not a function of circumstance. Greatness is largely a matter of conscious choice and discipline.", a: "Jim Collins" },
  { q: "I am no bird; and no net ensnares me: I am a free human being with an independent will.", a: "Charlotte Bronte" },
  { q: "If you have more than three priorities, you don't have any.", a: "Jim Collins" },
  { q: "There is no charm equal to tenderness of heart.", a: "Jane Austen" },
  { q: "What do we live for, if it is not to make life less difficult to each other?", a: "George Eliot" },
  { q: "No one is useless in this world who lightens the burdens of another.", a: "Charles Dickens" },
  { q: "Have a heart that never hardens, and a temper that never tires, and a touch that never hurts.", a: "Charles Dickens" },
  { q: "To travel hopefully is a better thing than to arrive.", a: "Robert Louis Stevenson" },
  { q: "Only those who will risk going too far can possibly find out how far one can go.", a: "T. S. Eliot" },
  { q: "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly.", a: "Langston Hughes" },
  { q: "There are years that ask questions and years that answer.", a: "Zora Neale Hurston" },
  { q: "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.", a: "Marcel Proust" },
  { q: "Stuff your eyes with wonder, live as if you'd drop dead in ten seconds.", a: "Ray Bradbury" },
  { q: "Within you there is a stillness and a sanctuary to which you can retreat at any time and be yourself.", a: "Hermann Hesse" },
  { q: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.", a: "Antoine de Saint-Exupery" },
  { q: "As for the future, your task is not to foresee it, but to enable it.", a: "Antoine de Saint-Exupery" },
  { q: "I hope for nothing. I fear nothing. I am free.", a: "Nikos Kazantzakis" },
  { q: "To err is human, to forgive divine.", a: "Alexander Pope" },
  { q: "A thing of beauty is a joy forever.", a: "John Keats" },
  { q: "If winter comes, can spring be far behind?", a: "Percy Bysshe Shelley" },
  { q: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", a: "John Milton" },
  { q: "To see a world in a grain of sand, and a heaven in a wild flower.", a: "William Blake" },
  { q: "To strive, to seek, to find, and not to yield.", a: "Alfred Tennyson" },
  { q: "The journey is better than the inn.", a: "Miguel de Cervantes" },
];
